# This file was generated by GoReleaser. DO NOT EDIT.
class Maestro < Formula
  desc "A straightforward service orchestrator"
  homepage "https://github.com/jexia/maestro"
  version "2.0.0-beta.16"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jexia/maestro/releases/download/v2.0.0-beta.16/maestro-2.0.0-beta.16-darwin-amd64.tar.gz"
    sha256 "fc14572275e3f8369260830b3dceea60f6b76142405718b44fc97b9135a758ad"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jexia/maestro/releases/download/v2.0.0-beta.16/maestro-2.0.0-beta.16-linux-amd64.tar.gz"
      sha256 "2d392551cc31da906628859b581f58025b235ac109035e0c08326464068d5ef8"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jexia/maestro/releases/download/v2.0.0-beta.16/maestro-2.0.0-beta.16-linux-arm64.tar.gz"
        sha256 "efbd3b909cf748a4a64d773cb52356aecc6b7f32e32d5c235843c33217f11232"
      else
        url "https://github.com/jexia/maestro/releases/download/v2.0.0-beta.16/maestro-2.0.0-beta.16-linux-arm.tar.gz"
        sha256 "d7e23a74196ab38d99f88a7240aea48466cd823868e58b8d8eb43ae51ec7c8d4"
      end
    end
  end

  def install
    bin.install "maestro"
  end

  test do
    system "#{bin}/maestro -v"
  end
end
