# This file was generated by GoReleaser. DO NOT EDIT.
class Maestro < Formula
  desc "A straightforward service orchestrator"
  homepage "https://github.com/jexia/maestro"
  version "2.0.0-beta.17"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jexia/maestro/releases/download/v2.0.0-beta.17/maestro-2.0.0-beta.17-darwin-amd64.tar.gz"
    sha256 "ce43410e5a1e1fce80d5ba186024628d8321c56ca54f0e17535a7f39b5751c95"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jexia/maestro/releases/download/v2.0.0-beta.17/maestro-2.0.0-beta.17-linux-amd64.tar.gz"
      sha256 "4ef03e1950566a296b36cbf2f9e028dca228ddab82c7ae06233983dc7238e9ca"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jexia/maestro/releases/download/v2.0.0-beta.17/maestro-2.0.0-beta.17-linux-arm64.tar.gz"
        sha256 "0f8b40294adecdc140e498f248b354bbb34a2777060546d13e545eb10931a669"
      else
        url "https://github.com/jexia/maestro/releases/download/v2.0.0-beta.17/maestro-2.0.0-beta.17-linux-arm.tar.gz"
        sha256 "badb2ab0f4a98a8907f781910bc0aec2dcfb6a4f27ea7f1256ed5183bf55a22a"
      end
    end
  end

  def install
    bin.install "maestro"
  end

  test do
    system "#{bin}/maestro -v"
  end
end
