# This file was generated by GoReleaser. DO NOT EDIT.
class Semaphore < Formula
  desc "A straightforward service orchestrator"
  homepage "https://github.com/jexia/semaphore"
  version "2.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jexia/semaphore/releases/download/v2.0.1/semaphore-2.0.1-darwin-amd64.tar.gz"
    sha256 "e773c7f10fa0b1afd03e75a82c6876a3a3a8c92500078d65e4a0ddda8c3c4f7b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jexia/semaphore/releases/download/v2.0.1/semaphore-2.0.1-linux-amd64.tar.gz"
      sha256 "a9345b7de1dba636b30cdf27974fe08ddb79d5bd36c9ef3c28b6a65cacc5e848"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jexia/semaphore/releases/download/v2.0.1/semaphore-2.0.1-linux-arm64.tar.gz"
        sha256 "47f1dc264b9e53340fda577bc0d3e6e1ea5ad0d1f9214e4800a55e223a78c5e1"
      else
        url "https://github.com/jexia/semaphore/releases/download/v2.0.1/semaphore-2.0.1-linux-arm.tar.gz"
        sha256 "3459731fb79eb1bbae965dc9132636f3ab5049f45e2ca1ed10f39d272b1b6a71"
      end
    end
  end

  def install
    bin.install "semaphore"
  end

  test do
    system "#{bin}/semaphore -v"
  end
end
