# This file was generated by GoReleaser. DO NOT EDIT.
class Semaphore < Formula
  desc "A straightforward service orchestrator"
  homepage "https://github.com/jexia/semaphore"
  version "2.0.0-beta.18"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jexia/semaphore/releases/download/v2.0.0-beta.18/semaphore-2.0.0-beta.18-darwin-amd64.tar.gz"
    sha256 "ca94dde42eb5aa8430e7306b328b0a40e4c3651b3a184b5cfe67fb84ad48364c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jexia/semaphore/releases/download/v2.0.0-beta.18/semaphore-2.0.0-beta.18-linux-amd64.tar.gz"
      sha256 "e71b9973d5bda0af75c40fbbbec08367961acd5eb920c10fe1b3bd6e8f894e36"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jexia/semaphore/releases/download/v2.0.0-beta.18/semaphore-2.0.0-beta.18-linux-arm64.tar.gz"
        sha256 "a11f67dbf605dd65b7481f0b9cc36ab70573d304f80a09258285fe2c03100d84"
      else
        url "https://github.com/jexia/semaphore/releases/download/v2.0.0-beta.18/semaphore-2.0.0-beta.18-linux-arm.tar.gz"
        sha256 "ecc3cb61ab6c962b12a9a528dff7e255d7730e43a2180cac6f57d28c89d0053b"
      end
    end
  end

  def install
    bin.install "semaphore"
  end

  test do
    system "#{bin}/semaphore -v"
  end
end
